version: '3.8'
services:
  odds-mentor-mongo-db:
    image: mongo
    container_name: odds-mentor-mongo-db
    ports:
      - "8088:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: odds-mentor
    networks:
      - backend-networks
    volumes:
      - ./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: mongod

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"

  mentor-api:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-booking/api-mentor:dev
    ports:
      - "8087:8080"
    restart: always
    networks:
      - backend-networks
      - frontend-networks
    depends_on:
      - odds-mentor-mongo-db
      - rabbitmq
    links:
      - odds-mentor-mongo-db
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=${MONGO_DB}
      - RABBIT_PORT=5672
      - SENDINBLUE_TOKEN=${SENDINBLUE_TOKEN}

  mentor-web:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-booking/web-mentor:dev
    ports:
      - "8089:80"
    restart: always
    networks:
      - frontend-networks
    depends_on:
      - odds-mentor-mongo-db
      - mentor-api

networks:
  backend-networks:
    driver: bridge
    name: backend-networks
  frontend-networks:
    driver: bridge
    name: frontend-networks


volumes:
  mongo-data:
    driver: local

      

