version: '3.8'
services:
  db:
    image: mongo
    ports:
      - 8088:27017
    container_name: odds-mentor-mongo-db
    networks:
      - backend-networks
    volumes:
      - mongo-data:/data/db

  mentor-api:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-mentor/api-mentor:dev
    ports:
      - 8087:8080
    restart: always
    networks:
      - backend-networks
      - frontend-networks
    depends_on:
      - db

  mentor-web:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-mentor/web-mentor:dev
    ports:
      - 80:80
    restart: always
    networks:
      - frontend-networks
    depends_on:
      - db
      - mentor-api

networks:
  backend-networks:
    driver: bridge
  frontend-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local

      

